Update pom.xml
There is an error triggered "java.lang.NoClassDefFoundError: org/apache/beam/sdk/testing/SerializableMatcher". The classpath is missing